# Generated by Django 4.2.6 on 2023-10-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='films',
            new_name='film',
        ),
    ]
